import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type PostDocument = HydratedDocument<Post>;

@Schema({ _id: false })
export class Thumbnail {
  @Prop({ type: Boolean, default: false })
  isRejected: boolean;

  @Prop({ type: String, required: true })
  url: string;

  @Prop({ type: Boolean, required: true, default: true })
  isAutoGenerated: boolean;
}

const ThumbnailSchema = SchemaFactory.createForClass(Thumbnail);

@Schema({
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
})
export class Post {
  @Prop({ type: String, required: true })
  userId: string;

  @Prop({ type: String, required: true })
  videoUrl: string;



}

export const PostSchema = SchemaFactory.createForClass(Post);
