import {
  IsArray,
  IsBoolean,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from 'class-validator';
import { Type } from 'class-transformer';

class Thumbnail {
  @IsBoolean()
  isRejected: boolean;

  @IsString()
  url: string;

  @IsBoolean()
  isAutoGenerated: boolean;
}

export class UpdatePostDto {
  @IsBoolean()
  @IsOptional()
  isDraft: boolean;







}
