import {
  IsArray,
  IsBoolean,
  IsOptional,
  IsString,
  ValidateNested,
  IsEnum,
} from 'class-validator';
import { LanguageEnum } from '../entities/post.type';
import { Type } from 'class-transformer';

class Thumbnail {
  @IsBoolean()
  isRejected: boolean;

  @IsString()
  url: string;

  @IsBoolean()
  isAutoGenerated: boolean;
}

export class UpdatePostDto {
  @IsBoolean()
  @IsOptional()
  isDraft: boolean;

  @IsEnum(LanguageEnum)
  @IsOptional()
  language: LanguageEnum;

  @IsString()
  @IsOptional()
  title: string;

  @IsString()
  @IsOptional()
  caption: string;

  @IsString()
  @IsOptional()
  description: string;

  @IsString()
  @IsOptional()
  videoUrl: string;

  @IsArray()
  @IsOptional()
  hashtag: string[];

  @IsArray()
  @IsOptional()
  @ValidateNested({ each: true })
  @Type(() => Thumbnail)
  thumbnail: Thumbnail[];
}
